# travis wants a language so we make it feel special
language: ruby
install: 
- cabal update
- cabal install shellcheck
script: ~/.cabal/binshellcheck --format tty puush
addons:
  apt:
    packages:
    - cabal-install
